### PR TITLE
✨Fix and change style pages verifiy email, make pages cuy universe teams✨

### PR DESCRIPTION
**Pull request by xrafffcode**
image

### CODE REVIEW

**Comment by deaaprizal** [comment]
versi mobile nya aman kah bro?

**Comment by xrafffcode** [comment]
> versi mobile nya aman kah bro?

aman banget

**Comment by xrafffcode** [comment]
image

**Comment by xrafffcode** [comment]
yang pages team itu dapet dari github api ya jadi datanua update otomatis

https://api.github.com/repos/deaaprizal/laract9/contributors?

**Comment by xrafffcode** [comment]
> versi mobile nya aman kah bro?

image

**Comment by deaaprizal** [comment]
thanks bro keren

**Comment by xrafffcode** [comment]
> thanks bro keren

Okey a sama², Sabi kali difollow akunku wkwkwk. Btw kenapa tadi ga live bang padahal nungguin

**Pull request merged**
