### PR TITLE
Add feature change password

### PR DESCRIPTION
**Pull request by mohrizkifajar**
Add feature **Change Password** in menu **Setting**.

image

image

### CODE REVIEW

**Review by deaaprizal — COMMENTED** [review]
wait for my review oke, need to check on my local 👍

**Comment by mohrizkifajar** [comment]
> wait for my review oke, need to check on my local 👍

Okay bang

**Comment by kbiits** [comment]
#106 Issue ini ga di close bang @deaaprizal ?

**Comment by kbiits** [comment]
btw @mohrizkifajar console.log di function updatePassword nya kelupaan di ilangin ?

**Pull request merged**
